version: "3.7"
services:
  mariadb:
    image: mariadb:10.5
    networks:
      - nginx-django
    volumes:
      - dbData:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: test_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test1234

  django_container:
    image: pinterest_gunicorn:3
    networks:
      - nginx-django
    volumes:
      - static:/home/pinterest/staticfiles
      - media:/home/pinterest/mediafiles

  nginx_container:
    image: nginx:1.19.5
    networks:
      - nginx-django
    volumes:
      - /home/user/nginx.conf:/etc/nginx/nginx.conf
      - static:/data/static
      - media:/data/media
    ports:
      - 80:80

networks:
  nginx-django:

volumes:
  static:
  media:
  dbData:
